---
abstract: 'Perl document, yes. Perl code, no damn way!'
author:
  - 'Adam Kennedy <adamk@cpan.org>, L<http://ali.as/>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-BadExample
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Acme-BadExample
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Acme-BadExample
version: 1.01
